# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo汇总' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'
  
  # Pods for Demo汇总

  target 'Demo汇总Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo汇总UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
